### ISSUE TITLE
Facebookloginの改善

### ISSUE THREAD

**Issue by n0dam1** [NaitoYuki/StackOverFlow#69]
### 事象
emailアドレスを登録していないfacebookユーザーがログインしようとするとログインできない。
### 原因
サインアップ時emailでユーザー検索しているがemailがないと適当なemailアドレスを作って割り当てている。ログイン時もemailでユーザー検索しているが適当なemailアドレスを割り当てているため、検索に引っかからないためログインできない。
### 対応
1. emailで検索
2. 1で検索できなかったら別の属性（~~検討中~~プロバイダとuidの複合キー）で検索

**Comment by n0dam1** [comment]
```ruby
auth = {
	provider: "facebook",
	uid: "hogeuid",
	info: {
      email: nil,
      image: "http://hoge_image_url.com"
    },
    extra: {
      raw_info: {
        name: "hogename"
      }
    }
}
auth1 = OmniAuth::AuthHash.new(auth);
user1 = User.find_for_facebook_oauth(auth1, nil)
User.find_for_facebook_oauth(auth1, user1)

```

**Comment by n0dam1** [comment]
```
[3] pry(main)> auth = {
[3] pry(main)*   provider: "facebook",
[3] pry(main)*   uid: "hogeuid",
[3] pry(main)*   info: {
[3] pry(main)*     email: nil, # email      \U+FFE3\U+FFAB\U+FFE3\U+FFE3\U+FFBC\U+FFE3\U+FFBF\U+FFE7\U+FFA1\U+FFE3
[3] pry(main)*     image: "http://hoge_image_url.com"      
[3] pry(main)*   },      
[3] pry(main)*   extra: {    
[3] pry(main)*     raw_info: {      
[3] pry(main)*       name: "hogename"        
[3] pry(main)*     }        
[3] pry(main)*   }      
[3] pry(main)* }  
=> {:provider=>"facebook",
 :uid=>"hogeuid",
 :info=>{:email=>nil, :image=>"http://hoge_image_url.com"},
 :extra=>{:raw_info=>{:name=>"hogename"}}}
[4] pry(main)> mock_auth = OmniAuth::AuthHash.new(auth);
[5] pry(main)> mock_auth
=> {"provider"=>"facebook",
 "uid"=>"hogeuid",
 "info"=>{"email"=>nil, "image"=>"http://hoge_image_url.com"},
 "extra"=>{"raw_info"=>{"name"=>"hogename"}}}
[6] pry(main)> mock_user = User.find_for_facebook_oauth(mock_auth, nil)
  User Load (19.6ms)  SELECT  "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT 1
  User Load (23.0ms)  SELECT  "users".* FROM "users" WHERE "users"."provider" = $1 AND "users"."uid" = $2 LIMIT 1  [["provider", "facebook"], ["uid", "hogeuid"]]
   (0.3ms)  BEGIN
  SQL (31.5ms)  INSERT INTO "users" ("name", "provider", "uid", "email", "image_url", "encrypted_password", "confirmed_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["name", "hogename"], ["provider", "facebook"], ["uid", "hogeuid"], ["email", "hogeuid-facebook@example.com"], ["image_url", "http://hoge_image_url.com"], ["encrypted_password", "$2a$11$JgStmZtg3O059N0GPWsiZedjeEGtEQ6Tq39a3rVa9wg8auwwgLDo6"], ["confirmed_at", "2017-06-20 13:14:27.203825"], ["created_at", "2017-06-20 13:14:27.207296"], ["updated_at", "2017-06-20 13:14:27.207296"]]
   (6.3ms)  COMMIT
=> #<User id: 23, email: "hogeuid-facebook@example.com", created_at: "2017-06-20 13:14:27", updated_at: "2017-06-20 13:14:27", name: "hogename", uid: "hogeuid", provider: "facebook", image_url: "http://hoge_image_url.com", avatar: nil>
[7] pry(main)> mock_user.present?
=> true
[8] pry(main)> mock_user.email
=> "hogeuid-facebook@example.com"
[9] pry(main)> mock_auth = OmniAuth::AuthHash.new(auth);
[10] pry(main)> mock_auth
=> {"provider"=>"facebook",
 "uid"=>"hogeuid",
 "info"=>{"email"=>nil, "image"=>"http://hoge_image_url.com"},
 "extra"=>{"raw_info"=>{"name"=>"hogename"}}}
[11] pry(main)> mock_login_user = User.find_for_facebook_oauth(mock_auth, nil)
  User Load (1.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT 1
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."provider" = $1 AND "users"."uid" = $2 LIMIT 1  [["provider", "facebook"], ["uid", "hogeuid"]]
=> #<User id: 23, email: "hogeuid-facebook@example.com", created_at: "2017-06-20 13:14:27", updated_at: "2017-06-20 13:14:27", name: "hogename", uid: "hogeuid", provider: "facebook", image_url: "http://hoge_image_url.com", avatar: nil>
[12] pry(main)> mock_login_user == mock_user
=> true
[13] pry(main)> 

```

**Comment by n0dam1** [comment]
ロジック修正前
```
[1] pry(main)> auth = {
[1] pry(main)*   provider: "facebook",
[1] pry(main)*   uid: "hogeuid",
[1] pry(main)*   info: {
[1] pry(main)*     email: nil, # email      \U+FFE3\U+FFAB\U+FFE3\U+FFE3\U+FFBC\U+FFE3\U+FFBF\U+FFE7\U+FFA1\U+FFE3
[1] pry(main)*     image: "http://hoge_image_url.com"      
[1] pry(main)*   },      
[1] pry(main)*   extra: {    
[1] pry(main)*     raw_info: {      
[1] pry(main)*       name: "hogename"        
[1] pry(main)*     }        
[1] pry(main)*   }      
[1] pry(main)* }  
=> {:provider=>"facebook",
 :uid=>"hogeuid",
 :info=>{:email=>nil, :image=>"http://hoge_image_url.com"},
 :extra=>{:raw_info=>{:name=>"hogename"}}}
[2] pry(main)> mock_auth = OmniAuth::AuthHash.new(auth);
[3] pry(main)> mock_auth
=> {"provider"=>"facebook",
 "uid"=>"hogeuid",
 "info"=>{"email"=>nil, "image"=>"http://hoge_image_url.com"},
 "extra"=>{"raw_info"=>{"name"=>"hogename"}}}
[4] pry(main)> mock_user = User.find_for_facebook_oauth(mock_auth, nil)
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /Users/n0dam1/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
  User Load (19.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT 1
   (0.3ms)  BEGIN
  SQL (22.7ms)  INSERT INTO "users" ("name", "provider", "uid", "email", "image_url", "encrypted_password", "confirmed_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["name", "hogename"], ["provider", "facebook"], ["uid", "hogeuid"], ["email", "hogeuid-facebook@example.com"], ["image_url", "http://hoge_image_url.com"], ["encrypted_password", "$2a$11$Yb.PZp3n.NvCmY6Ycdlh/uugmGkQCkAhwECqwzy3aBVCIuFgC6bv6"], ["confirmed_at", "2017-06-20 13:17:01.323283"], ["created_at", "2017-06-20 13:17:01.329639"], ["updated_at", "2017-06-20 13:17:01.329639"]]
   (0.8ms)  COMMIT
=> #<User id: 24, email: "hogeuid-facebook@example.com", created_at: "2017-06-20 13:17:01", updated_at: "2017-06-20 13:17:01", name: "hogename", uid: "hogeuid", provider: "facebook", image_url: "http://hoge_image_url.com", avatar: nil>
[5] pry(main)> mock_user.present?
=> true
[6] pry(main)> mock_user.email
=> "hogeuid-facebook@example.com"
[7] pry(main)> mock_auth = OmniAuth::AuthHash.new(auth);
[8] pry(main)> mock_auth
=> {"provider"=>"facebook",
 "uid"=>"hogeuid",
 "info"=>{"email"=>nil, "image"=>"http://hoge_image_url.com"},
 "extra"=>{"raw_info"=>{"name"=>"hogename"}}}
[9] pry(main)> mock_login_user = User.find_for_facebook_oauth(mock_auth, nil)
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE "users"."email" IS NULL LIMIT 1
   (0.2ms)  BEGIN
  SQL (16.7ms)  INSERT INTO "users" ("name", "provider", "uid", "email", "image_url", "encrypted_password", "confirmed_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["name", "hogename"], ["provider", "facebook"], ["uid", "hogeuid"], ["email", "hogeuid-facebook@example.com"], ["image_url", "http://hoge_image_url.com"], ["encrypted_password", "$2a$11$K/aGBziS7FoIsVuu9LmC8u9pngFy4O9XYBIB4g56xXx7azdMAioxO"], ["confirmed_at", "2017-06-20 13:17:33.267945"], ["created_at", "2017-06-20 13:17:33.269844"], ["updated_at", "2017-06-20 13:17:33.269844"]]
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(hogeuid-facebook@example.com) already exists.
: INSERT INTO "users" ("name", "provider", "uid", "email", "image_url", "encrypted_password", "confirmed_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
   (0.2ms)  ROLLBACK
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(hogeuid-facebook@example.com) already exists.
: INSERT INTO "users" ("name", "provider", "uid", "email", "image_url", "encrypted_password", "confirmed_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
from /Users/n0dam1/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:606:in `exec_prepared'
[10] pry(main)> mock_login_user == mock_user
=> false
[11] pry(main)> 

```
